services:
  falco:
    extends:
      file: ./monitoring/docker-compose.yml
      service: falco

  prometheus:
    extends:
      file: ./monitoring/docker-compose.yml
      service: prometheus

  grafana:
    extends:
      file: ./monitoring/docker-compose.yml
      service: grafana

  loki:
    extends:
      file: ./monitoring/docker-compose.yml
      service: loki

  tempo:
    extends:
      file: ./monitoring/docker-compose.yml
      service: tempo

  otel-collector:
    extends:
      file: ./monitoring/docker-compose.yml
      service: otel-collector

  promtail:
    extends:
      file: ./monitoring/docker-compose.yml
      service: promtail

networks:
  logiflow-security-net:
    external: true

volumes:
  grafana_data:
